FROM jenkins/inbound-agent:4.3-4

ARG JENKINS_HOME=/home/jenkins
ARG user=jenkins
ARG group=jenkins

USER root

COPY rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
COPY helm /usr/local/bin/helm
COPY kubectl /usr/local/bin/kubectl
COPY docker /usr/local/bin/docker
RUN update-ca-certificates \
    && chmod +x /usr/local/bin/helm /usr/local/bin/kubectl /usr/local/bin/docker

USER ${user}

COPY --chown=${user}:${group} id_rsa $JENKINS_HOME/.ssh/id_rsa
COPY --chown=${user}:${group} id_rsa.pub $JENKINS_HOME/.ssh/id_rsa.pub
RUN chmod 0700 $JENKINS_HOME/.ssh \
    && chmod 0600 $JENKINS_HOME/.ssh/id_rsa \
    && chmod 0644 $JENKINS_HOME/.ssh/id_rsa.pub
    
