spec:
  template:
    spec:
      containers:
      - name: ingress-nginx-controller
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.33.0
        ports:
         - containerPort: 2222
           hostPort: 2222
